packages:
  - "."

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  netlify: true
  ngrok: true
  prisma: true
  sharp: true
  unix-dgram: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - msgpackr-extract
  - netlify
  - ngrok
  - prisma
  - sharp
  - unix-dgram
  - unrs-resolver
