packages:
  - "."

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - msgpackr-extract
  - netlify
  - ngrok
  - prisma
  - sharp
  - unix-dgram
  - unrs-resolver
